pipeline {
    agent {
        node {
            label 'agent-node'
        }
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World here iam'
            }
        }
    }
}